import type { GameStateSnapshot, RuntimeMetrics, TestRunOptions } from '../types/GameTypes.js';
export declare class GameApp {
    private readonly mount;
    private readonly canvas;
    private readonly ctx;
    private readonly uiRoot;
    private readonly loader;
    private readonly rng;
    private readonly stateMachine;
    private readonly stageSystem;
    private readonly waveSystem;
    private readonly controlSystem;
    private readonly backgroundSystem;
    private readonly autoAttackSystem;
    private readonly saveSystem;
    private readonly hud;
    private readonly playerBulletPool;
    private readonly enemyBulletPool;
    private readonly enemyPool;
    private readonly explosionPool;
    private readonly boss;
    private runState;
    private player;
    private moduleChoices;
    private selectedModule?;
    private installedSelectedModule;
    private lastTime;
    private fps;
    private running;
    private endingRecorded;
    constructor(mount: HTMLElement);
    start(): Promise<void>;
    startNewRun(options?: Partial<TestRunOptions>): void;
    private enterCurrentStage;
    private loop;
    private update;
    private handlePlayerInput;
    private spawnEnemies;
    private spawnEnemyFromWave;
    private updateEnemies;
    private updateBoss;
    private fireBossPattern;
    private updateBullets;
    private updateExplosions;
    private updateAutoAttack;
    private spawnEnemyBullet;
    private handleCollisions;
    private killEnemy;
    private spawnExplosion;
    private enterStageResult;
    private renderStageResult;
    private enterVictory;
    private enterDefeat;
    private renderGameResult;
    private togglePause;
    private renderPause;
    private showMenu;
    private renderLoading;
    private draw;
    private drawTitleBackdrop;
    private drawEntities;
    private drawImageOrShape;
    private drawSmallHpBar;
    private clearEnemyBullets;
    private clearCombatObjects;
    private resize;
    getStateSnapshot(): GameStateSnapshot;
    getMetrics(): RuntimeMetrics;
    private installTestHooksIfNeeded;
    private getEnemySnapshots;
    private spawnTestEnemy;
    private spawnTestBoss;
}
